config/routes.rb
Rails.application.routes.draw do

  root 'titles#index'

  resources :titles, except: [:destroy] do 
    collection do 
      get :search, to: "titles#search"
    end
    get 'sign_in', to: "titles#index"
  end

  resources :titles, only: [:show] do
    collection do
      post :search, to: "titles#search"
    end 
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :titles

	def recent_videos
		titles.first(6)
	end

end

app/models/title.rb
class Title < ActiveRecord::Base
	belongs_to :category

	def self.search_by_headline(search_term)
		return [] if search_term.blank?
		where("headline LIKE ?", "%#{search_term}%").order("created_at DESC")
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories1 = Category.all

	end

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController

	def new
	end

	def index
		@categories1 = Category.all
	end

	def show
		@title1 = Title.find(params[:id])
	end

	def search
		@search1 = Title.search_by_headline(params[:search_term])
		if @search1
			render 'titles/search'
		else 
			flash[:error] = 'Sorry, no videos matched your search.'
			redirect_to '/'
		end

	end

	private


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flixnet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= form_tag search_titles_path do %>
<input class="search-query" name="search-term" type="text" placeholder="search for titles here"></input>
<input type="submit" class="button" value="search" href="" >

<% end %>

<%= yield %>

</body>
</html>

app/views/titles/index.html.erb
	<p>
		<% @categories1.each do |zyx| %>
		<a><%= zyx.genus %></a>

		<% zyx.recent_videos.each do |poster| %>
			<form method="post">
				<a href="/titles/<%= poster.id %>"><img src='/assets/<%= poster.image_small %>'></a>
			</form>
				<% end %>
<% end %>
</p>


<h2>This is titles/index.html.erb</h2>

app/views/titles/search.html.erb
<article class="title_category">
  <% @search1.each do |video| %>
    <div class="span2">
      <%= link_to video do %>
        <img src='/<%= video.image_small %>' style='height:200px' class='indent-a' />
      <% end %>
    </div>
  <% end %>
</article>

app/views/titles/show.html.erb
<form method='post'>
<br/>
<%= @title1.headline %>
<br/>
<img src='/assets/<%= @title1.image_big %>'>
<br/>
<br/>
<%= @title1.description %>
</form>